name: Docker Build
on: [push]
jobs:
  job:
    name: yocto docker build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          cd ./yocto
          docker build -t yocto:dunfell .
